-- MySQL Script generated by MySQL Workbench
-- Fri Jan 17 09:04:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(100) NULL,
  `PrimerApellido` VARCHAR(100) NULL,
  `SegundoApellido` VARCHAR(100) NULL,
  `Usuario` VARCHAR(50) NULL,
  `Password` VARCHAR(50) NULL,
  `FechaCrea` DATETIME NULL,
  `UsuarioCrea` VARCHAR(50) NULL,
  `Valido` INT NULL,
  `Roll` VARCHAR(100) NULL,
  `Rfc` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Examen` (
  `IdExamen` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `Clave` VARCHAR(2) NULL,
  `Tiempo` INT NULL,
  `CalificacionAprobatoria` DECIMAL(18,6) NULL,
  `FechaCrea` DATETIME NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`IdExamen`, `Usuario_Id`),
  INDEX `fk_Examen_Usuario1_idx` (`Usuario_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Examen_Usuario1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `mydb`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pregunta` (
  `IdPregunta` INT NOT NULL AUTO_INCREMENT,
  `Tipo` INT NULL,
  `Nombre` VARCHAR(1000) NULL,
  `Valor` DECIMAL(18,6) NULL,
  `Valido` INT NULL,
  `FechaCrea` DATETIME NULL,
  `UsuarioCrea` VARCHAR(50) NULL,
  `Examen_IdExamen` INT NOT NULL,
  PRIMARY KEY (`IdPregunta`, `Examen_IdExamen`),
  INDEX `fk_Pregunta_Examen_idx` (`Examen_IdExamen` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_Examen`
    FOREIGN KEY (`Examen_IdExamen`)
    REFERENCES `mydb`.`Examen` (`IdExamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Respuesta` (
  `IdRespuesta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(1000) NULL,
  `Valor` DECIMAL(18,6) NULL,
  `Valido` INT NULL,
  `FechaCrea` DATETIME NULL,
  `UsuarioCrea` VARCHAR(50) NULL,
  `Pregunta_IdPregunta` INT NOT NULL,
  `Pregunta_Examen_IdExamen` INT NOT NULL,
  PRIMARY KEY (`IdRespuesta`, `Pregunta_IdPregunta`, `Pregunta_Examen_IdExamen`),
  INDEX `fk_Respuesta_Pregunta1_idx` (`Pregunta_IdPregunta` ASC, `Pregunta_Examen_IdExamen` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`Pregunta_IdPregunta` , `Pregunta_Examen_IdExamen`)
    REFERENCES `mydb`.`Pregunta` (`IdPregunta` , `Examen_IdExamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsuarioExamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UsuarioExamen` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Clave` VARCHAR(50) NULL,
  `TiempoTrascurrio` VARCHAR(10) NULL,
  `Aprobado` INT NULL,
  `FechaCrea` DATETIME NULL,
  `Valido` INT NULL,
  `Examen_IdExamen` INT NOT NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Examen_IdExamen`, `Usuario_Id`),
  INDEX `fk_UsuarioExamen_Examen1_idx` (`Examen_IdExamen` ASC) VISIBLE,
  INDEX `fk_UsuarioExamen_Usuario1_idx` (`Usuario_Id` ASC) VISIBLE,
  CONSTRAINT `fk_UsuarioExamen_Examen1`
    FOREIGN KEY (`Examen_IdExamen`)
    REFERENCES `mydb`.`Examen` (`IdExamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioExamen_Usuario1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `mydb`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evaluacion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Pregunta_IdPregunta` INT NOT NULL,
  `Respuesta_IdRespuesta` INT NOT NULL,
  `UsuarioExamen_Id` INT NOT NULL,
  `EsCorrecta` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`, `Pregunta_IdPregunta`, `Respuesta_IdRespuesta`, `UsuarioExamen_Id`),
  INDEX `fk_Resultado_Pregunta1_idx` (`Pregunta_IdPregunta` ASC) VISIBLE,
  INDEX `fk_Resultado_Respuesta1_idx` (`Respuesta_IdRespuesta` ASC) VISIBLE,
  INDEX `fk_Evaluacion_UsuarioExamen1_idx` (`UsuarioExamen_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Resultado_Pregunta1`
    FOREIGN KEY (`Pregunta_IdPregunta`)
    REFERENCES `mydb`.`Pregunta` (`IdPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultado_Respuesta1`
    FOREIGN KEY (`Respuesta_IdRespuesta`)
    REFERENCES `mydb`.`Respuesta` (`IdRespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_UsuarioExamen1`
    FOREIGN KEY (`UsuarioExamen_Id`)
    REFERENCES `mydb`.`UsuarioExamen` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
